name = 'team-daangn-com'
type = 'javascript'
account_id = 'aad5c82543cd1f267b89737d0f56405e'
usage_model = 'unbound'
zone_id = ''
route = ''
workers_dev = true

vars = { GH_JOBBOARD_TOKEN = "daangn" }

[build]
command = 'yarn esbuild src/worker/index.ts --bundle --outfile=dist/worker.js --format=esm'

[build.upload]
format = 'service-worker'
