nodeLinker: node-modules
nmMode: hardlinks-global

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  daangn:
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-berry.cjs
