packages:
  - "_packages/**"
  - "_workers/**"
  - "www.example.com"
  - "team.daangn.com"
  - "careers.ca.karrotmarket.com"
  - "careers.jp.karrotmarket.com"
  - "uk.karrotmarket.com"
  - "ca.karrotmarket.com"
  - "us.karrotmarket.com"
  - "jp.karrotmarket.com"
  - "ads-local.daangn.com"
  - "about.daangn.com"
