# yaml-language-server: $schema=https://raw.githubusercontent.com/daangn/seed-design/%40seed-design/icon%400.2.0/packages/icon/schema/schema.json

# https://www.figma.com/file/58VvezaS8z1FsIOr9KFHKW/icon?node-id=0%3A1
# 아이콘의 실제 모습은 위 링크에서 확인할 수 있습니다.
# 예: icon_add_circle_fill | icon_add_circle_regular
icons:
  - icon_backward_regular
  - icon_search_regular
  - icon_expand_more_regular
  - icon_chevron_right_regular
  - icon_call_fill
  - icon_close_regular
  - icon_forward_regular
  - icon_ios_share_regular

componentPath: src/Icon.tsx
