name = 'prismic-if-greenhouse'
type = 'javascript'
compatibility_date = '2022-02-17'
account_id = 'aad5c82543cd1f267b89737d0f56405e'
usage_model = 'unbound'
workers_dev = true

[build]
command = 'yarn esbuild src/worker.ts --bundle --outfile=dist/worker.js --format=esm'

[build.upload]
format = 'service-worker'
