name: Build (& Deploy) jp.karrotmarket.com

on:
  workflow_dispatch:
    inputs:
      clean:
        description: Clean before Build
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - '.github/workflows/build-jp_karrotmarket_com.yml'
      - jp.karrotmarket.com/**/*
      - yarn.lock
    branches:
      - main
  push:
    paths:
      - '.github/workflows/build-jp_karrotmarket_com.yml'
      - jp.karrotmarket.com/**/*
      - yarn.lock
    branches:
      - main
  repository_dispatch:
    types: jp.karrotmarket.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build (& Deploy)
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Restore Gatsby Cache
        uses: actions/cache@v3
        with:
          path: |
            jp.karrotmarket.com/.cache
            jp.karrotmarket.com/public
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Clean before Build
        if: ${{ github.event.inputs.clean == 'true' }}
        run: |
          yarn workspace jp.karrotmarket.com clean

      - name: Build jp.karrotmarket.com
        run: |
          yarn workspace jp.karrotmarket.com build --log-pages --prefix-paths
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          HOT_ARTICLE_API_SPECIAL_KEY: ${{ secrets.HOT_ARTICLE_API_SPECIAL_KEY }}
          ASSET_PREFIX: https://assets.jp.karrotmarket.com
          NODE_ENV: production
          CI: true

      - name: Deploy jp.karrotmarket.com
        if: github.event_name != 'pull_request'
        uses: jonelantha/gatsby-s3-action@v2
        with:
          dest-s3-bucket: jp.karrotmarket.com
          cloudfront-id-to-invalidate: E3OLUPD92LI886
          public-source-path: jp.karrotmarket.com/public
          sync-delete: false
